import type { Metadata } from "next";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Contact",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" cz-shortcut-listen="true">
      <body className={inter.className} cz-shortcut-listen="true">
        {children}
      </body>
    </html>
  );
}
